version: '3.8'
services:
  app:
    build: .
    image: car-api:latest
    ports:
      - "8000:8000"
    environment:
      PYTHONUNBUFFERED: "1"
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres:17.6-bookworm
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
